name: Main workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.04.x
          - 4.05.x
          - 4.06.x
          - 4.07.x
          - 4.08.x
          - 4.09.x
          - 4.10.x
          - 4.11.x
          - 4.12.x
        libev:
          - true
          - false
        ppx:
          - true
        local-packages:
          - "*.opam"
        coverage:
          - false
        include:
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.4.12.0+options,ocaml-option-flambda,ocaml-option-musl,ocaml-option-static
            libev: false
            ppx: true
            local-packages: "*.opam"
            coverage: false
          - os: ubuntu-latest
            ocaml-compiler: 4.12.x
            libev: true
            ppx: true
            local-packages: "*.opam"
            coverage: true
          - os: macos-latest
            ocaml-compiler: 4.12.x
            libev: true
            ppx: true
            local-packages: "*.opam"
            coverage: false
          - os: windows-latest
            ocaml-compiler: 4.12.x
            libev: false
            ppx: true
            local-packages: "*.opam"
            coverage: false
          - os: ubuntu-latest
            ocaml-compiler: 4.02.x
            libev: true
            ppx: false
            local-packages: |
              *.opam
              !lwt_ppx.opam
            coverage: false
          - os: ubuntu-latest
            ocaml-compiler: 4.02.x
            libev: false
            ppx: false
            local-packages: |
              *.opam
              !lwt_ppx.opam
            coverage: false
          - os: ubuntu-latest
            ocaml-compiler: 4.03.x
            libev: true
            ppx: false
            local-packages: |
              *.opam
              !lwt_ppx.opam
            coverage: false
          - os: ubuntu-latest
            ocaml-compiler: 4.03.x
            libev: false
            ppx: false
            local-packages: |
              *.opam
              !lwt_ppx.opam
            coverage: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-depext-flags: --with-test
          opam-local-packages: ${{ matrix.local-packages }}

      - run: opam depext conf-libev --install
        if: ${{ matrix.libev == true }}

      - run: opam install . --deps-only --with-test
        if: ${{ matrix.ppx == true }}

      - run: opam install lwt_luv lwt_react lwt --deps-only --with-test
        if: ${{ matrix.ppx == false }}

      - run: opam exec -- make build
        if: ${{ matrix.ppx == true }}

      - run: opam exec -- dune build --only-packages lwt_luv,lwt_react,lwt
        if: ${{ matrix.ppx == false }}

      - run: opam exec -- make test
        if: ${{ matrix.ppx == true }}

      - run: opam exec -- dune runtest --only-packages lwt_luv,lwt_react,lwt
        if: ${{ matrix.ppx == false }}

      - run: opam exec -- make ppx_let-test-deps ppx_let-test
        if: ${{ matrix.ppx == true }}

      - run: opam install bisect_ppx
        if: ${{ matrix.coverage == true }}

      - run: opam exec -- make coverage
        if: ${{ matrix.coverage == true }}

      - run: opam exec -- bisect-ppx-report send-to Coveralls
        if: ${{ matrix.coverage == true }}
        env:
          COVERALLS_REPO_TOKEN: ${{ github.token }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
